import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

// This backend is intentionally a macOS/launchd fixture.  Use the same POSIX
// path semantics on every CI runner so Windows does not turn the fixture into
// a mixture of win32 paths and macOS launchd paths.
vi.mock('node:path', async (original) => {
  const actual = await original<typeof import('node:path')>();
  return { ...actual, ...actual.posix };
});

import { basename, join } from 'node:path';

const fake = vi.hoisted(() => ({
  files: new Set<string>(), links: new Set<string>(),
  definitions: new Map<string, { label: string; args: string[]; envFile?: string; root?: string }>(),
  jobs: new Map<string, { pid: string; temporary?: boolean }>(),
  calls: [] as string[][],
  write: vi.fn(), mkdir: vi.fn(),
}));
const fakeNode = '/fake/bin/node';
const home = '/fake/home';
const packageBin = '/pkg/bin';
const larkEntry = join(packageBin, 'lark-channel-bridge.mjs');
const wecomEntry = join(packageBin, 'wecom-channel-bridge.mjs');
const botEnvFile = '/private/bot.env';
const otherEnvFile = '/private/other.env';
const larkHome = '/fake/home/.lark-channel';
const lark = 'ai.lark-channel-bridge.bot.codex';
const wecom = 'ai.wecom-channel-bridge.test';
const plist = (label: string) => join(home, 'Library', 'LaunchAgents', `${label}.plist`);
const argv1 = process.argv[1];
const platform = process.platform;
const originalExitCode = process.exitCode;
const originalExecPath = Object.getOwnPropertyDescriptor(process, 'execPath');

vi.mock('node:os', async (original) => ({
  ...await original<typeof import('node:os')>(),
  homedir: () => home, userInfo: () => ({ uid: 501 }),
}));
vi.mock('../../../src/config/paths', () => ({ paths: { rootDir: larkHome, profile: 'codex', configFile: `${larkHome}/config.json` } }));
vi.mock('node:fs', async (original) => ({
  ...await original<typeof import('node:fs')>(),
  existsSync: (path: string) => fake.files.has(path),
  lstatSync: (path: string) => ({ isFile: () => fake.files.has(path), isSymbolicLink: () => fake.links.has(path) }),
  realpathSync: (path: string) => { if (!fake.files.has(path)) throw new Error('secret path unavailable'); return path; },
  readdirSync: () => [...fake.definitions.keys()].map((path) => basename(path)),
  mkdirSync: fake.mkdir,
  writeFileSync: (path: string, content: string, options: unknown) => {
    fake.write(path, content, options);
    if (fake.files.has(path)) throw Object.assign(new Error('exists'), { code: 'EEXIST' });
    fake.files.add(path);
    // Values generated by this fixture's explicit setup, not copied from any real plist.
    fake.definitions.set(path, { label: 'ai.wecom-channel-bridge.test',
      args: [fakeNode, wecomEntry], envFile: botEnvFile });
  },
}));
vi.mock('node:child_process', async (original) => ({
  ...await original<typeof import('node:child_process')>(),
  spawnSync: (bin: string, args: string[]) => {
    fake.calls.push([bin, ...args]);
    if (bin === '/usr/bin/plutil') {
      const definition = fake.definitions.get(args[args.length - 1]!);
      const key = args[1];
      const value = key === 'Label' ? definition?.label : key === 'ProgramArguments'
        ? JSON.stringify(definition?.args) : key === 'EnvironmentVariables.LARK_CHANNEL_HOME'
          ? definition?.root : definition?.envFile;
      return { status: value ? 0 : 1, stdout: value ?? '', stderr: '' };
    }
    const label = args[1]?.replace('gui/501/', '') ?? '';
    if (args[0] === 'list') return { status: 0, stdout: [...fake.jobs].map(([name, job]) => `${job.pid}\t0\t${name}`).join('\n'), stderr: '' };
    if (args[0] === 'print') {
      const job = fake.jobs.get(label);
      return { status: job ? 0 : 113, stderr: '', stdout: job ? `gui/501/${label} = {\npath = ${job.temporary ? '(submitted by launchctl[1])' : '/fake/service.plist'}\nstate = running\npid = ${job.pid}\nruns = 1\n}` : '' };
    }
    if (args[0] === 'bootstrap') {
      const definition = fake.definitions.get(args[2]!);
      if (!definition) return { status: 5, stdout: '', stderr: 'secret' };
      fake.jobs.set(definition.label, { pid: definition.label.includes('wecom') ? '200' : '100' });
    }
    return { status: 0, stdout: '', stderr: '' };
  },
}));

const { runAllServices } = await import('../../../src/daemon/bot-fleet');

beforeEach(() => {
  fake.files.clear(); fake.links.clear(); fake.definitions.clear(); fake.jobs.clear(); fake.calls.length = 0;
  fake.write.mockClear(); fake.mkdir.mockClear();
  Object.defineProperty(process, 'execPath', { ...originalExecPath, value: fakeNode });
  for (const path of [fakeNode, larkEntry, wecomEntry, botEnvFile, otherEnvFile]) fake.files.add(path);
  fake.files.add(plist(lark));
  fake.definitions.set(plist(lark), {
    label: lark, args: [fakeNode, larkEntry, 'run', '--profile', 'codex'], root: larkHome,
  });
  process.argv[1] = larkEntry;
  Object.defineProperty(process, 'platform', { value: 'darwin', configurable: true });
  vi.spyOn(process, 'kill').mockReturnValue(true);
  vi.spyOn(console, 'log').mockImplementation(() => {});
  process.exitCode = originalExitCode;
});
afterEach(() => {
  if (originalExecPath) Object.defineProperty(process, 'execPath', originalExecPath);
  if (argv1 === undefined) process.argv.splice(1, 1);
  else process.argv[1] = argv1;
  Object.defineProperty(process, 'platform', { value: platform, configurable: true });
  process.exitCode = originalExitCode;
  vi.useRealTimers(); vi.restoreAllMocks();
});

function live() {
  fake.jobs.set(lark, { pid: '100' });
  fake.jobs.set(wecom, { pid: '200', temporary: true });
}
const options = { profile: 'codex', wecomService: wecom };
const effects = () => fake.calls.filter((call) => call[0] === '/bin/launchctl' && !['print', 'list'].includes(call[1]!));

describe('fleet macOS backend with fake launchctl and files', () => {
  it('uses a fixed POSIX node executable for canonical service validation', () => {
    expect(process.execPath).toBe(fakeNode);
    expect(basename(process.execPath)).toBe('node');
  });

  it('leaves both live services alone, including a submitted WeCom job', async () => {
    live();
    await runAllServices('start', options);
    expect(effects()).toEqual([]);
    expect(fake.write).not.toHaveBeenCalled();
    expect(console.log).toHaveBeenCalledWith(expect.stringContaining('pid=200'));
    expect(process.exitCode).not.toBe(1);
  });
  it('creates only a missing persistent WeCom definition without unloading the live job', async () => {
    live();
    await runAllServices('start', { ...options, wecomEnvFile: botEnvFile });
    expect(fake.write).toHaveBeenCalledOnce();
    expect(fake.write).toHaveBeenCalledWith(plist(wecom), expect.stringContaining('<key>WECOM_ENV_FILE</key>'),
      { encoding: 'utf8', mode: 0o600, flag: 'wx' });
    expect(effects()).toEqual([]);
    await runAllServices('start', { ...options, wecomEnvFile: botEnvFile });
    expect(fake.write).toHaveBeenCalledOnce();
    expect(effects()).toEqual([]);
  });
  it('does not replace an existing definition with another configuration', async () => {
    live();
    await runAllServices('start', { ...options, wecomEnvFile: botEnvFile });
    await runAllServices('start', { ...options, wecomEnvFile: otherEnvFile });
    expect(fake.write).toHaveBeenCalledOnce();
    expect(process.exitCode).toBe(1);
    expect(effects()).toEqual([]);
    expect(console.log).toHaveBeenCalledWith(expect.stringContaining('状态未确认'));
  });
  it('uses enable/bootstrap for both stopped services and no shell or kill', async () => {
    vi.useFakeTimers();
    const pending = runAllServices('start', { ...options, wecomEnvFile: botEnvFile });
    await vi.runAllTimersAsync(); await pending;
    expect(effects()).toEqual([
      ['/bin/launchctl', 'enable', `gui/501/${lark}`], ['/bin/launchctl', 'bootstrap', 'gui/501', plist(lark)],
      ['/bin/launchctl', 'enable', `gui/501/${wecom}`], ['/bin/launchctl', 'bootstrap', 'gui/501', plist(wecom)],
    ]);
    expect(process.exitCode).not.toBe(1);
    expect(fake.jobs.size).toBe(2);
  });
  it('refuses a symlinked service definition and does not stop the healthy peer', async () => {
    live(); fake.links.add(plist(lark));
    await runAllServices('start', options);
    expect(process.exitCode).toBe(1);
    expect(effects()).toEqual([]);
    expect(fake.write).not.toHaveBeenCalled();
  });
  it.each(['wrong-label', 'extra-script', 'shell-wrapper', 'missing-node', 'missing-entry'])(
    'rejects %s without changing either service definition or stopping the healthy peer', async (kind) => {
      live();
      const definition = fake.definitions.get(plist(lark))!;
      if (kind === 'wrong-label') definition.label = 'unrelated.job';
      if (kind === 'extra-script') definition.args.push('/pkg/extra.mjs');
      if (kind === 'shell-wrapper') {
        fake.files.add('/bin/zsh');
        definition.args = ['/bin/zsh', '-c', 'do-not-execute'];
      }
      if (kind === 'missing-node') fake.files.delete(fakeNode);
      if (kind === 'missing-entry') fake.files.delete(larkEntry);
      const before = JSON.stringify([...fake.definitions]);
      await runAllServices('start', options);
      expect(process.exitCode).toBe(1);
      expect(effects()).toEqual([]);
      expect(fake.write).not.toHaveBeenCalled();
      expect(JSON.stringify([...fake.definitions])).toBe(before);
      expect(console.log).toHaveBeenCalledWith(expect.stringContaining('pid=200'));
    },
  );

  it('status does not install, rewrite, enable, bootstrap, or read env-file contents', async () => {
    live();
    await runAllServices('status', options);
    expect(fake.write).not.toHaveBeenCalled(); expect(fake.mkdir).not.toHaveBeenCalled();
    expect(fake.calls.every((call) => call[0] === '/bin/launchctl' && call[1] === 'print')).toBe(true);
  });
});
